name: CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: endevco/aube-action@f82ca2f6c943dbde1904945d9f0ee1a0faf8e945 # v1.0.0
        with:
          version: 1.9.1
          node-version: "24"
      - run: aube ci
      - run: aube run fmt:check
      - run: aube run lint
      - run: aube run build
